In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('data/combined.csv', parse_dates=[2])
df

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,AL011851,UNNAMED,1851-06-25,0,,HU,28.0N,94.8W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,AL011851,UNNAMED,1851-06-25,600,,HU,28.0N,95.4W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,AL011851,UNNAMED,1851-06-25,1200,,HU,28.0N,96.0W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,AL011851,UNNAMED,1851-06-25,1800,,HU,28.1N,96.5W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,AL011851,UNNAMED,1851-06-25,2100,L,HU,28.2N,96.8W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75237,EP222015,SANDRA,2015-11-28,1200,,LO,21.7N,109.0W,35,1002,...,0,0,0,0,0,0,0,0,0,0
75238,EP222015,SANDRA,2015-11-28,1800,,LO,22.4N,108.7W,30,1007,...,0,0,0,0,0,0,0,0,0,0
75239,EP222015,SANDRA,2015-11-29,0,,LO,23.1N,108.3W,30,1008,...,0,0,0,0,0,0,0,0,0,0
75240,EP222015,SANDRA,2015-11-29,600,,LO,23.5N,107.9W,25,1009,...,0,0,0,0,0,0,0,0,0,0
75241,EP222015,SANDRA,2015-11-29,1200,,LO,24.2N,107.7W,20,1010,...,0,0,0,0,0,0,0,0,0,0

In [39]:
df.dtypes

ID                          object
Name                        object
Date                datetime64[ns]
Time                         int64
Event                       object
Status                      object
Latitude                    object
Longitude                   object
Maximum Wind               float64
Minimum Pressure           float64
Low Wind NE                float64
Low Wind SE                float64
Low Wind SW                float64
Low Wind NW                float64
Moderate Wind NE           float64
Moderate Wind SE           float64
Moderate Wind SW           float64
Moderate Wind NW           float64
High Wind NE               float64
High Wind SE               float64
High Wind SW               float64
High Wind NW               float64
dtype: object

In [18]:
print('Ends in 00:', (df.Time % 100 == 0).sum())
print('Ends in 15:', (df.Time % 100 == 15).sum())
print('Ends in 30:', (df.Time % 100 == 30).sum())
print('Ends in 45:', (df.Time % 100 == 45).sum())
(df.Time % 100).value_counts()

Ends in 00: 75110
Ends in 15: 17
Ends in 30: 72
Ends in 45: 21

0     75110
30       72
45       21
15       17
25        3
40        3
10        3
20        2
5         2
50        2
35        2
46        1
34        1
52        1
56        1
13        1
Name: Time, dtype: int64

In [38]:
df.loc[df['Maximum Wind'] < 0, 'Maximum Wind'] = np.nan
df.loc[df['Minimum Pressure'] < 0, 'Minimum Pressure'] = np.nan
for low_wind in ['Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW']:
    df.loc[df[low_wind] < 0, low_wind] = np.nan
for moderate_wind in ['Moderate Wind NE', 'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW']:
    df.loc[df[moderate_wind] < 0, moderate_wind] = np.nan
for high_wind in ['High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']:
    df.loc[df[high_wind] < 0, high_wind] = np.nan
df.describe()

,Time,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
count,75242.000000,74904.000000,31769.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000,12308.000000
mean,905.236517,51.620221,993.398691,60.222213,55.001219,37.391128,46.631053,18.806061,16.989357,12.042980,14.746506,6.648928,5.856354,4.233425,5.359522
std,671.407615,25.030448,18.754211,73.461174,71.551498,59.268536,64.615816,33.861571,33.237911,25.787593,28.979360,16.317595,15.136829,11.693356,14.094177
min,0.000000,10.000000,872.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,600.000000,30.000000,986.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1200.000000,45.000000,1000.000000,45.000000,30.000000,0.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1700.000000,70.000000,1007.000000,100.000000,90.000000,60.000000,75.000000,30.000000,30.000000,20.000000,25.000000,0.000000,0.000000,0.000000,0.000000
max,2330.000000,185.000000,1024.000000,710.000000,600.000000,640.000000,1180.000000,360.000000,300.000000,330.000000,360.000000,180.000000,250.000000,150.000000,180.000000

In [37]:
low_wind = ['Low Wind NE', 'Low Wind SE', 'Low Wind SW', 'Low Wind NW']
for lw in low_wind:
    df.loc[df[lw] < 0, lw] = np.nan
df.describe()

,Time,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
count,75242.000000,74904.000000,31769.000000,12308.000000,12308.000000,12308.000000,12308.000000,75242.000000,75242.000000,75242.000000,75242.000000,75242.000000,75242.000000,75242.000000,75242.000000
mean,905.236517,51.620221,993.398691,60.222213,55.001219,37.391128,46.631053,-832.508453,-832.805627,-833.614750,-833.172510,-834.497103,-834.626751,-834.892228,-834.708022
std,671.407615,25.030448,18.754211,73.461174,71.551498,59.268536,64.615816,376.730809,376.050162,374.125576,375.163319,372.043479,371.742185,371.121593,371.551726
min,0.000000,10.000000,872.000000,0.000000,0.000000,0.000000,0.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
25%,600.000000,30.000000,986.000000,0.000000,0.000000,0.000000,0.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
50%,1200.000000,45.000000,1000.000000,45.000000,30.000000,0.000000,30.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
75%,1700.000000,70.000000,1007.000000,100.000000,90.000000,60.000000,75.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
max,2330.000000,185.000000,1024.000000,710.000000,600.000000,640.000000,1180.000000,360.000000,300.000000,330.000000,360.000000,180.000000,250.000000,150.000000,180.000000